# Generated by Django 4.2 on 2023-04-21 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0002_alter_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
