# Generated by Django 4.2 on 2023-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_remove_staff_first_name_remove_staff_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
