# Generated by Django 4.1.7 on 2023-05-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_first_name_remove_staff_last_name_and_more'),
        ('staff', '0005_remove_transactionitem_book_and_more'),
    ]

    operations = [
    ]
