# Generated by Django 4.2 on 2023-04-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_account_options_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
    ]
