# Generated by Django 4.2 on 2023-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_account_is_staff_account_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
