# Generated by Django 4.1.7 on 2023-04-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('cover_price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_image', models.ImageField(upload_to='')),
                ('status', models.IntegerField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.bookinfo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
            ],
        ),
    ]
