# Generated by Django 4.1.7 on 2023-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='book_image',
            field=models.ImageField(default=None, null=True, upload_to='static/assets/img/book'),
        ),
    ]
