# Generated by Django 4.2 on 2023-05-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ("book", "0005_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="book_image",
            field=models.ImageField(
                default="static/des/book_cover.png",
                null=True,
                upload_to="static/assets/img/book",
            ),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='cover_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
