# Generated by Django 4.2 on 2023-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="book_image",
            field=models.ImageField(
                default="static/des/book_cover.png",
                null=True,
                upload_to="static/assets/img/book",
            ),
        ),
    ]
