# Generated by Django 4.2 on 2023-05-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_book_book_id_alter_bookinfo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Waiting"), (2, "Borrowing"), (0, "Available")], default=0
            ),
        ),
    ]
