# Generated by Django 4.1.7 on 2023-05-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
