# Generated by Django 4.1.7 on 2023-05-01 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_alter_bookinfo_book_image'),
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rental_date', models.DateField(default=datetime.date.today)),
                ('return_date', models.DateField(default=datetime.date(2023, 5, 11))),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Borrowing'), (2, 'Returned'), (3, 'Expired')], default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.transaction')),
            ],
        ),
    ]
