# Generated by Django 4.2 on 2023-05-04 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_transaction_return_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="return_date",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="status",
        ),
        migrations.AddField(
            model_name="transaction",
            name="regis_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="transaction",
            name="trans_status",
            field=models.IntegerField(choices=[(1, "Waiting"), (0, "Done")], default=1),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="return_date",
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="rental_date",
            field=models.DateField(default=None),
        ),
    ]
