# Generated by Django 4.2 on 2023-05-04 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0008_alter_transaction_rental_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="store",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.store"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
