# Generated by Django 4.2 on 2023-05-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_transaction_store_alter_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trans_status",
            field=models.IntegerField(
                choices=[(1, "Waiting"), (2, "Borrowing"), (0, "Done")], default=1
            ),
        ),
    ]
