# Generated by Django 4.1.7 on 2023-05-06 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_transaction_trans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 5, 13)),
        ),
    ]
