# Generated by Django 4.1.7 on 2023-05-08 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_status'),
        ('cart', '0011_transaction_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 5, 15)),
        ),
    ]
