# Generated by Django 4.1.7 on 2023-05-10 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cartitem_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='return_date',
            field=models.DateField(default=datetime.date(2023, 5, 17)),
        ),
    ]
