# Generated by Django 4.2 on 2023-05-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0015_alter_transaction_return_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="return_date",
        ),
    ]
