# Generated by Django 4.2 on 2023-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="expired_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
