# Generated by Django 4.2 on 2023-04-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_user_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static/des/userava.png", upload_to="home/img/"
            ),
        ),
    ]
