# Generated by Django 4.2 on 2023-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static/des/userava.png", upload_to="static/assets/img/team/"
            ),
        ),
    ]
