# Generated by Django 4.1.7 on 2023-05-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
