# Generated by Django 4.1.7 on 2023-05-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
