# Generated by Django 4.1.7 on 2023-05-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_id'),
        ('user', '0012_rate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
            preserve_default=False,
        ),
    ]
